<?php

function greeting_menu() {
	$items = array();
	$items['hello_friend'] = array(
			'title' => "Hello Friend!",
			'page callback' => 'say_hello',
			'access callback' => TRUE,
			'type' => MENU_NORMAL_ITEM,
		);
	$items['goodbye'] = array(
			'title' => "Goodbye Friend!"
			'page callback' => 'say_goodbye',
			'access callback' => TRUE, 
			'type' => MENU_NORMAL_ITEM,
		);
	return $items; 
}

function say_hello(){
	return '<p style="font-weight:bold;font-style:italic;">Hello, Welcome to My Blog!</p>';
	
}
