<?php

function greeting_menu() {
	$items = array();
	$items['hello_friend'] = array(
			'title' => "Hello Friend!",
			'page callback' => 'say_hello',
			'access callback' => TRUE,
			'type' => MENU_CALLBACK,
		);
	$items['goodbye'] = array(
			'title' => "Goodbye Friend!",
			'page callback' => 'say_goodbye',
			'access callback' => TRUE, 
			'type' => MENU_CALLBACK,
		);
	return $items; 
}

function say_hello(){
	return '<p style="font-weight:bold;font-style:italic;">Hello, Welcome to My Blog!</p>';
	
}

function say_goodbye() {
	return '<p style="font-weight:bold;font-style:italic;">Please Visit Us Again!</p>';
}

function greeting_user_login() {
	$_GET['destination'] = 'hello_friend';
}

funtion greeting_user_logout(){
	$_GET['destination'] = 'goodbye';
}